### PR TITLE
Two issues solved:

### PR DESCRIPTION
**Pull request by vikiCoder**
1.)Select all while selecting webmails
2.)Save selected webmails in inbox and show back in onResume

### CODE REVIEW

**Comment by crearo** [comment]
This looks great. I'll go through this thoroughly tomorrow, and if everything's alright, I'll merge asap :)

**Comment by vikiCoder** [comment]
Hello, 
I hope that you have seen the changes that I've made. Actually I am new to github and opensource, so please tell and guid me if I've done something wrong so that I can correct it.

**Comment by crearo** [comment]
Hey,
I had a look at the code, and it all looks great. 
1. You've followed all conventions - nomenclature, method names. access modifiers of variables, etc
2. You've followed appropriate guidelines by Android on restoring instance states - which can be slightly tricky at times.
So, great job! 

There are a couple of minor changes that I'll make - for example the switch case in the MainActivity where all strings are referenced using "quotes" - instead, reference strings by creating them in Constants.java in the util package. That way, silly errors like spelling mistakes won't get in the way of development. Apart from that, all is fine from your side. :) 
I'm really busy this week, and will merge the pull request this weekend. :+1: 

Also, till then, since you've had a fair look at the code and know how everything is working, do you think you could work on a couple of the other issues? Pull up to load more [issue here](https://github.com/CreaRo/DAWebmail/issues/17) is something lots of users have been writing to me about. If you do work on it, I suggest you to create a new branch in your repository with the name load-more and work on that branch. 

For next time, remember when sending a pull request, work on a separate branch, and keep your master branch clean (up to date with the repo you fork from). This is because if you make any changes to your master branch now, they will show up here on this pull request.

**Comment by vikiCoder** [comment]
Ok I will definitely try other issues.

**Comment by crearo** [comment]
Hey, I'm really sorry I'm taking this much time to merge your request. I've been super busy of late. 
I'll definitely do so this weekend. Thanks for your patience!

**Comment by crearo** [comment]
Great work :)

**Pull request merged**
